cleanup

diff --git a/.github/workflows/workflow.ci.yml b/.github/workflows/workflow.ci.yml
--- a/.github/workflows/workflow.ci.yml
+++ b/.github/workflows/workflow.ci.yml
@@ -15,6 +15,9 @@ on:
       - main
     paths:
       - "mkdocs_file_filter_plugin/**"
+      - "tests/**"
+      - "schema*.json"
+      - "mkdocs*.yml"
       - "poetry.lock"
       - "pyproject.toml"
       - "setup.py"
@@ -43,6 +46,88 @@ jobs:
         with:
           comment-summary-in-pr: true
 
+  codeql-analyze:
+    if: ${{ github.event_name == 'push' || (github.event_name == 'pull_request' && !github.event.pull_request.draft && !contains(github.event.head_commit.message, 'skip-codeql')) }}
+    name: CodeQL Analyze
+    runs-on: ubuntu-latest
+    permissions:
+      actions: read
+      security-events: write
+    strategy:
+      fail-fast: false
+      matrix:
+        language: ["python"]
+        # CodeQL supports [ 'cpp', 'csharp', 'go', 'java', 'javascript', 'python', 'ruby' ]
+        # Use only 'java' to analyze code written in Java, Kotlin or both
+        # Use only 'javascript' to analyze code written in JavaScript, TypeScript or both
+        # Learn more about CodeQL language support at https://aka.ms/codeql-docs/language-support
+    steps:
+      - name: Checkout Repo
+        uses: actions/checkout@v3
+
+      # Initializes the CodeQL tools for scanning.
+      - name: Initialize CodeQL
+        uses: github/codeql-action/init@v2
+        with:
+          languages: ${{ matrix.language }}
+          queries: security-extended
+          # If you wish to specify custom queries, you can do so here or in a config file.
+          # By default, queries listed here will override any specified in a config file.
+          # Prefix the list here with "+" to use these queries and those in the config file.
+
+          # Details on CodeQL's query packs refer to : https://docs.github.com/en/code-security/code-scanning/automatically-scanning-your-code-for-vulnerabilities-and-errors/configuring-code-scanning#using-queries-in-ql-packs
+          # queries: security-extended,security-and-quality
+
+      # Autobuild attempts to build any compiled languages  (C/C++, C#, Go, or Java).
+      # If this step fails, then you should remove it and run the build manually (see below)
+      - name: Autobuild
+        uses: github/codeql-action/autobuild@v2
+
+      # ℹ️ Command-line programs to run using the OS shell.
+      # 📚 See https://docs.github.com/en/actions/using-workflows/workflow-syntax-for-github-actions#jobsjob_idstepsrun
+
+      #   If the Autobuild fails above, remove it and uncomment the following three lines.
+      #   modify them (or add more) to build your code if your project, please refer to the EXAMPLE below for guidance.
+
+      # - run: |
+      #     echo "Run, Build Application using script"
+      #     ./location_of_script_within_repo/buildscript.sh
+
+      - name: Perform CodeQL Analysis
+        uses: github/codeql-action/analyze@v2
+        with:
+          category: "/language:${{matrix.language}}"
+          upload: false
+          output: codeql-results
+
+      - name: Upload Sarif Artifact
+        uses: actions/upload-artifact@v3
+        with:
+          name: Analyses Results (SARIF)
+          path: codeql-results
+          if-no-files-found: warn
+
+  codeql-results:
+    if: ${{ github.event_name == 'push' || (github.event_name == 'pull_request' && !github.event.pull_request.draft && !contains(github.event.head_commit.message, 'skip-codeql')) }}
+    name: CodeQL Results
+    needs:
+      - codeql-analyze
+    runs-on: ubuntu-latest
+    steps:
+      - name: Checkout Repo
+        uses: actions/checkout@v3
+
+      - name: Download Sarifs
+        uses: actions/download-artifact@v3
+        with:
+          path: codeql-results
+
+      - name: Upload Results
+        uses: github/codeql-action/upload-sarif@v2
+        with:
+          sarif_file: codeql-results
+          wait-for-processing: true
+
   lint:
     if: ${{ github.event_name == 'push' || (github.event_name == 'pull_request' && !github.event.pull_request.draft) }}
     name: Lint
@@ -62,32 +147,101 @@ jobs:
 
       - name: Install dependencies
         run: |
+          poetry self add "poethepoet[plugin]"
           poetry self add "poetry-dynamic-versioning[plugin]"
-          poetry install --verbose --all-extras --only=dev
+          poetry poe install-dev
 
-      # - name: Run ruff
-      #   run: poetry run ruff -v check .
-
-      - name: Run mypy
-        run: poetry run mypy --config-file pyproject.toml
+      - name: Run Ruff
+        run: poetry poe ruff-check
 
       - name: Run isort
-        run: poetry run isort --settings-path pyproject.toml --check-only .
+        run: poetry poe isort-check
 
-      - name: Run black
-        run: poetry run black --config pyproject.toml --check .
+      - name: Run Black
+        run: poetry poe black-check
+      - name: Run Flake8
+        run: poetry poe flake8
 
-      - name: Run flake8
-        run: poetry run flake8 --count .
+      - name: Run PyDocstyle
+        run: poetry poe pydocstyle
 
-      - name: Run bandit
-        run: poetry run bandit --configfile pyproject.toml --recursive .
+      - name: Run MyPy
+        run: poetry poe mypy
 
-  test-self:
+      - name: Run PyLint
+        run: poetry poe pylint
+
+      - name: Run Bandit
+        run: poetry poe bandit
+
+  test:
     if: ${{ github.event_name == 'push' || (github.event_name == 'pull_request' && !github.event.pull_request.draft) }}
-    name: Test (self)
+    name: Test
     needs:
       - lint
+    permissions:
+      issues: read
+      checks: write
+      pull-requests: write
+    runs-on: ubuntu-latest
+    steps:
+      - name: Checkout Repo
+        uses: actions/checkout@v3
+
+      - name: Install Poetry
+        run: pipx install poetry
+
+      - name: Setup Python
+        uses: actions/setup-python@v4
+        with:
+          python-version-file: .python-version
+          cache: poetry
+
+      - name: Install dependencies
+        run: |
+          poetry self add "poethepoet[plugin]"
+          poetry self add "poetry-dynamic-versioning[plugin]"
+          poetry poe install-dev
+
+      - name: Run PyTest
+        run: poetry poe test
+
+      - name: Publish Test Results
+        uses: dorny/test-reporter@v1
+        if: ${{ always() }}
+        with:
+          name: Test Results
+          path: "*-junit.xml"
+          reporter: java-junit
+
+      - name: Write LCOV Report to Job Summary
+        uses: livewing/lcov-job-summary@v1
+        with:
+          lcov: coverage.lcov
+
+      - name: Write LCOV Report to PR as comment
+        uses: romeovs/lcov-reporter-action@master
+        with:
+          github-token: ${{ github.token }}
+          lcov-file: coverage.lcov
+          delete-old-comments: true
+          title: Code Coverage Report
+
+      - name: Upload Test and Coverage results
+        uses: actions/upload-artifact@v3
+        with:
+          name: Test and Coverage Results
+          path: |
+            *-junit.xml
+            coverage.xml
+            coverage.lcov
+            htmlcov/*
+
+  test-mkdocs-self:
+    if: ${{ github.event_name == 'push' || (github.event_name == 'pull_request' && !github.event.pull_request.draft) }}
+    name: Test MkDocs (self)
+    needs:
+      - test
     strategy:
       fail-fast: false
       matrix:
@@ -109,20 +263,21 @@ jobs:
 
       - name: Install dependencies
         run: |
+          poetry self add "poethepoet[plugin]"
           poetry self add "poetry-dynamic-versioning[plugin]"
-          poetry install --verbose --without=dev
+          poetry poe install
 
       - name: Test Build
-        run: poetry build --verbose
+        run: poetry poe build
 
       - name: Test MkDocs build
-        run: poetry run mkdocs build --verbose --config-file mkdocs.yml
+        run: poetry poe mkdocs-build --config-file mkdocs.yml
 
-  test-plugins:
+  test-mkdocs-plugins:
     if: ${{ github.event_name == 'pull_request' && !github.event.pull_request.draft }}
-    name: Test (plugins)
+    name: Test MkDocs (plugins)
     needs:
-      - test-self
+      - test-mkdocs-self
     runs-on: ubuntu-latest
     steps:
       - name: Checkout Repo
@@ -139,11 +294,12 @@ jobs:
 
       - name: Install dependencies
         run: |
+          poetry self add "poethepoet[plugin]"
           poetry self add "poetry-dynamic-versioning[plugin]"
-          poetry install --verbose --with=dev
+          poetry poe install-dev
 
       - name: Test Build
-        run: poetry build --verbose
+        run: poetry poe build
 
       - name: Test MkDocs build
-        run: poetry run mkdocs build --verbose --config-file mkdocs.plugins.yml
+        run: poetry poe mkdocs-build --config-file mkdocs.plugins.yml
